require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Include:
    - Gemfile
    - Rakefile
    - config.ru
    - apps/**/*.rb
    - lib/**/*.rb
    - config/**/*.rb
    - spec/**/*.rb
    - db/**/*.rb
  Exclude:
    - Rakefile

#
# Linters
#

#
# Naming
#

#
# Metrics
#
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - apps/web/application.rb

#
# Style
#
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

#
# RSpec
#
RSpec/DescribeClass:
  Exclude:
    - spec/**/features/*

#
# Capybara
#
